#+TITLE: Valokepakko notes

These notes are best read on Github or [[http://orgmode.org/manual/HTML-Export-commands.html#HTML-Export-commands][exported to HTML with Emacs org-mode]].
* Interfaces
** Button based interface

1. Hold button
2. Start drawing image based on relative position
   - The image is wrapped when hitting the edge, maybe a sound could play when
     this occurs

The benefit of this is that we have better control when the image starts
drawing, so that we don't start the exposure in the middle of the animation.

** Automatic interface
No button press needed. The image is always drawn based on the relative position.

** Orientation based interface

*** Basic idea
Hold the LED strip vertical and tilt it to either side.

Some considerations:
1. LEDs should be brighter on the top
2. How to change the frames?
   - Calculate them in the Python script?
   - Calculate them on the fly?

*** Orientation accuracy

In [[https://github.com/myrjola/Valokepakko/commit/32c92aa023f4dfb88f160cd728e6584ffcac206a][32c92aa]] I tested the accuracy in degrees. The noise seems to be ±0.5 degrees.
So we can say we have ~1 degree accuracy.

** Integrating the position

*** Get the position
- We get the acceleration on one axis
  - We have to integrate it twice to get the position
- When we have the relative position we can calculate which frame to show in the
  animation. We should have some way to measure it in metric units so that we
  can change the frames in relation to the LED strip dimensions.

*** What about using the speed?

**** Calibration stage

The problem we noticed during the demo session on the lecture 1.12.2015 is that
you need to give the sensor a sudden kick when you start moving. Calmly starting
the motion won't be noticed in all the noise. So maybe we need some kind of
calibration stage.

1. Push button to start calibration
2. Kick the strip into motion (not a real kick, just a fast impulse)
3. Determine the speed from the kick
4. Start drawing the image using constant speed

**** Calibration demo

Use a led or speaker to show every tick.

One button to start calibration.

***** How to read the signal?

We get values for X and Y with the demo code the values are ~5000 at no tilt and
~3700 and ~6200 at full tilt. There is some noise in the signal.

**** Viability

According to [[http://www.chrobotics.com/library/accel-position-velocity][this source]] using an accelerometer won't be viable for speed and position
calculation.

Orientation seems to be viable according to [[http://learn.parallax.com/kickstart/28017][the manufacturer]].

**** Memsic 2125 Dual-axis Accelerometer

***** Resources

https://www.parallax.com/product/28017

Good resource for Arduino: http://learn.parallax.com/kickstart/28017


***** Reading the study guide

Chapter 3 in [[https://www.parallax.com/sites/default/files/downloads/28029-Smart-Sensors-Text-v1.0.pdf][Smart Sensors and Applications]]

- Use atan to get the angle

*** Orientation of a wheel to distance travelled

Install the accelerometer on a wheel and calculate the orientation based on the
angle deltas.

Problems:
- Rotation will be hard because of the wires
  - Maybe there's some kind of rotating wire?
- All the problems of the wheel-based approach:
  - Cumbersome, needs more equipment
  - Can't move up and down

* Memory limitations

** Available memory in the Arduino

We will have problems with the limited memory available on the Arduino.

The Arduino has three memory spaces:
- Flash
  - 32kb - 5kb for the bootloader
  - program code
  - non-volatile
  - Variables declared in code isn't automatically added here
    - You have to use avr/pgmspace.h. See [[https://www.arduino.cc/en/Reference/PROGMEM][PROGMEM tutorial]].
- EEPROM
  - 1kb
  - non-volatile
  - Too small for images
- SRAM
  - 2kb
  - volatile
  - includes the heap and stack
  - Too small for images
** Compressing images

The LED strip supports 24-bit RGB-colors. The strip has 60 programmable LEDs,
that means that the uncompressed storage space needed for lighting the whole
strip is src_calc{60*24/8/1024} kb. If we want to store a 60 \times 60 pixel
image we will need src_calc{60*60*24/8/1024} kb.

One way around this is to decrease the available colors. The idea is to define a
palette array with 256 colors, they can be referenced with one byte. So the
image becomes an array of bytes, which reference the palette array. Now the
storage requirement for one 60 \times 60 pixel image becomes
src_calc{(60*60 + 3*256)/1024} kb.

* Data gathering

** Testing parameters with timer
*** 20 millis with wrapping 32 brightness 4 sec exposure

Image too dim not as pronounced

*** 40 millis with wrapping 64 brightness 4 sec exposure

These were good settings. next we switched to

*** without wrapping and increased exposure to 10 seconds

This gave good results

** Official data gathering

*** Yhteiset parametrit

3 m kamerasta

2.5 m kävelty matka

18mm (matches about 30 mm standard)

Panasonic Lumix DMC GM1

Zoom objektiivi 12-32 mm

Laskelmallinen kohinavaimennus (shutter noise reduction) pois päältä

Aukko 11

Kuva Naukio nimisestä kissasta

Adafruit valoisuus 64

*** Ajastus

20 ms sarakkeiden välillä

*** Tilt

Ei tarvittu valoisuuden säätöä

*** Pyörä

Hauska bugi jossa kiihtyvyysanturi pyöri 180 astetta pinnan ympäri kun pyörää
vieritettiin. Tämä johti peilattuun kuvaan, jota oli vaika vikaselvittää.
